//! modal-rust runtime: the frozen runner protocol seam.
//!
//! This crate is recompiled on **every** dev run and baked into **every** deploy
//! image, so it keeps a minimal dependency surface (only `serde`, `serde_json`,
//! `anyhow`, and a hand-rolled arg parser) — no Modal / network / Python deps
//! (boundaries.md §1).
//!
//! It provides:
//! - [`HandlerFn`] — a bare `fn` pointer (static dispatch — no `Box<dyn>`, no
//!   vtable).
//! - [`RunnerError`] — the five-kind error taxonomy serialized into the frozen
//!   failure envelope.
//! - the [`codec`] module — a JSON [`codec::Codec`] over bytes.
//! - the [`typed!`] macro — builds a monomorphized wrapper `fn` and yields its
//!   pointer.
//! - [`Registry`] — `BTreeMap<&'static str, HandlerFn>` with duplicate-name
//!   rejection.
//! - [`run_cli`] — parses the three runner flags, runs exactly one handler under
//!   `catch_unwind`, and prints exactly one JSON envelope to stdout.

use std::backtrace::Backtrace;
use std::cell::RefCell;
use std::collections::BTreeMap;
use std::panic::{self, AssertUnwindSafe};
use std::sync::Once;

use serde::Serialize;

/// A handler reduced to a bare `fn` pointer: bytes in, bytes out (boundaries.md
/// §3). No `dyn`, no `Box`, no vtable — every [`Registry`] entry is a
/// monomorphized free function reached through one cheap indirect jump after the
/// name lookup.
pub type HandlerFn = fn(&[u8]) -> Result<Vec<u8>, RunnerError>;

/// A DECODE-ONLY checker reduced to a bare `fn` pointer: it runs EXACTLY the
/// handler's `codec::decode::<In>(input)` step and discards the value, NEVER calling
/// the user's function body. It returns `Ok(())` when the input decodes into the
/// entrypoint's `In` and [`RunnerError::Decode`] otherwise.
///
/// The CLI invokes a built runner's `--check-input` mode (which calls this) to
/// VALIDATE `--input` LOCALLY and fail fast — with no Modal call and no body
/// execution — when the input cannot be decoded. Generated by [`typed_check!`]
/// alongside the [`typed!`] handler, so the checker's `In` is the SAME type the
/// handler decodes.
pub type CheckFn = fn(&[u8]) -> Result<(), RunnerError>;

/// A SNAPSHOT-PRIME hook reduced to a bare `fn` pointer: it FORCES a `#[cls]`
/// singleton's `get_or_init` (running its `#[enter]` exactly once) and DISCARDS the
/// value, returning `Ok(())` on success. Populated ONLY for snapshot-enabled
/// `#[cls]` methods; `None` for plain functions and non-snapshot classes.
///
/// The serve loop calls every registered prime on a `{"kind":"prime"}` frame
/// (BEST-EFFORT — a per-fn error is logged and skipped, never crashing the loop) so
/// the class's `#[enter]` runs INSIDE Modal's memory-snapshot freeze window. Because
/// it routes through the same `OnceLock` `get_or_init` the first real request would,
/// a class shared by several method-registrations is primed at most once even if its
/// prime fn is invoked N times, and a missed prime degrades to the existing lazy
/// `#[enter]` (correctness floor) rather than re-running.
pub type PrimeFn = fn() -> Result<(), RunnerError>;

/// The frozen failure taxonomy (boundaries.md §2). The runner models failure as a
/// Rust enum that **wraps** the user's error rather than stringifying it early, so
/// the monomorphized [`typed!`] wrapper can preserve structure.
#[derive(Debug)]
pub enum RunnerError {
    /// Input was not valid JSON, or valid JSON that failed to deserialize into the
    /// handler's `In`.
    Decode(String),
    /// `--entrypoint` named a handler not present in the [`Registry`].
    UnknownEntrypoint(String),
    /// The handler returned `Err(_)`. `message` is the `Display` / anyhow chain;
    /// `details` is the serialized user error when its type is `Serialize`, else
    /// `null`.
    Function {
        /// `Display` / anyhow-chain rendering of the user's error.
        message: String,
        /// The structurally serialized user error when `E: Serialize`, else `None`.
        details: Option<serde_json::Value>,
    },
    /// The handler's `Out` failed to serialize (e.g. non-string map keys, NaN).
    /// Must **not** be reported as [`RunnerError::Panic`].
    Encode(String),
    /// The handler unwound. `message` + `backtrace` are captured via a panic hook
    /// plus `catch_unwind`.
    Panic {
        /// The panic payload message.
        message: String,
        /// A captured `std::backtrace::Backtrace` rendering.
        backtrace: String,
    },
}

impl RunnerError {
    /// The frozen `kind` discriminant string for the failure envelope.
    pub fn kind(&self) -> &'static str {
        match self {
            RunnerError::Decode(_) => "decode_error",
            RunnerError::UnknownEntrypoint(_) => "unknown_entrypoint",
            RunnerError::Function { .. } => "function_error",
            RunnerError::Encode(_) => "encode_error",
            RunnerError::Panic { .. } => "panic",
        }
    }

    /// The human-readable `message` field for the failure envelope.
    pub fn message(&self) -> &str {
        match self {
            RunnerError::Decode(m) => m,
            RunnerError::UnknownEntrypoint(m) => m,
            RunnerError::Function { message, .. } => message,
            RunnerError::Encode(m) => m,
            RunnerError::Panic { message, .. } => message,
        }
    }

    /// The optional structural `details` field (the wrapped user error).
    pub fn details(&self) -> Option<&serde_json::Value> {
        match self {
            RunnerError::Function { details, .. } => details.as_ref(),
            _ => None,
        }
    }

    /// The `backtrace` field; non-empty only for the [`RunnerError::Panic`] kind.
    pub fn backtrace(&self) -> &str {
        match self {
            RunnerError::Panic { backtrace, .. } => backtrace,
            _ => "",
        }
    }

    /// Build a [`RunnerError::Function`] from a user error, preserving structure
    /// when the error type is [`Serialize`].
    ///
    /// This is the entry point the [`typed!`] macro uses for `Serialize` errors.
    /// `details = serde_json::to_value(&e).ok()` (boundaries.md §2). For anyhow
    /// (and other opaque) errors, callers use [`RunnerError::function_opaque`]
    /// which sets `details = None`.
    pub fn function<E>(e: E) -> Self
    where
        E: std::fmt::Display + Serialize,
    {
        let message = e.to_string();
        let details = serde_json::to_value(&e).ok();
        RunnerError::Function { message, details }
    }

    /// Build a [`RunnerError::Function`] from an opaque (non-`Serialize`) user
    /// error such as `anyhow::Error`. `details` is `None`; `message` is the
    /// `Display` rendering (the full anyhow chain for `anyhow::Error`).
    pub fn function_opaque<E>(e: E) -> Self
    where
        E: std::fmt::Display,
    {
        RunnerError::Function {
            message: e.to_string(),
            details: None,
        }
    }

    /// Render this error into the frozen failure envelope value
    /// `{"ok":false,"error":{"kind":..,"message":..,"details":<json|null>,"backtrace":..}}`.
    pub fn to_envelope(&self) -> serde_json::Value {
        serde_json::json!({
            "ok": false,
            "error": {
                "kind": self.kind(),
                "message": self.message(),
                "details": self.details().cloned().unwrap_or(serde_json::Value::Null),
                "backtrace": self.backtrace(),
            }
        })
    }
}

impl std::fmt::Display for RunnerError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}: {}", self.kind(), self.message())
    }
}

impl std::error::Error for RunnerError {}

/// JSON wire-format codec over bytes (boundaries.md §3, codec-neutral seam). A
/// future `--input-format cbor` would add a sibling impl here without touching
/// [`HandlerFn`] or [`Registry`].
pub mod codec {
    use super::RunnerError;
    use serde::de::DeserializeOwned;
    use serde::Serialize;

    /// Decode input bytes into a handler's `In`. A failure (invalid JSON or
    /// wrong-shape JSON) maps to [`RunnerError::Decode`].
    pub fn decode<T: DeserializeOwned>(input: &[u8]) -> Result<T, RunnerError> {
        serde_json::from_slice(input).map_err(|e| RunnerError::Decode(e.to_string()))
    }

    /// Encode a handler's `Out` into output bytes. A failure (e.g. non-string map
    /// keys, NaN) maps to [`RunnerError::Encode`] — never `panic`.
    pub fn encode<T: Serialize>(value: &T) -> Result<Vec<u8>, RunnerError> {
        serde_json::to_vec(value).map_err(|e| RunnerError::Encode(e.to_string()))
    }
}

/// `typed!(f)` generates a **monomorphized wrapper `fn`** for the handler `f` and
/// yields its [`HandlerFn`] pointer (boundaries.md §3). decode/call/encode are all
/// inlined/monomorphized for `f`'s concrete `In`/`Out`/`Err`.
///
/// The user error is wrapped onto [`RunnerError::Function`]: `details` is the
/// serialized error when the error type is `Serialize`, else `null`. The selection
/// is resolved at compile time by autoref specialization (see
/// [`__macro_support`]), so `anyhow::Result` handlers land on `details = null`
/// while a `Serialize` error populates `details`.
#[macro_export]
macro_rules! typed {
    ($f:path) => {{
        fn __wrap(
            input: &[u8],
        ) -> ::core::result::Result<::std::vec::Vec<u8>, $crate::RunnerError> {
            let arg = $crate::codec::decode(input)?;
            match $f(arg) {
                ::core::result::Result::Ok(out) => $crate::codec::encode(&out),
                ::core::result::Result::Err(e) => {
                    // Inherent-priority specialization (boundaries.md §2): the
                    // inherent `Wrap<E>::to_runner_error` (requires `E: Serialize`,
                    // populates `details`) wins over the `FunctionErrorOpaque` trait
                    // method (`details = null`, covers `anyhow::Error`) at this
                    // monomorphic call site whenever its bound is satisfied; otherwise
                    // resolution falls through to the trait method. The trait must be
                    // in scope for the fallback; the inherent method needs no import.
                    // When the handler's error is `Serialize`, the inherent method is
                    // chosen and this import is (expectedly) unused.
                    #[allow(unused_imports)]
                    use $crate::__macro_support::FunctionErrorOpaque as _;
                    ::core::result::Result::Err($crate::__macro_support::Wrap(e).to_runner_error())
                }
            }
        }
        __wrap as $crate::HandlerFn
    }};
}

/// `typed_check!(f)` generates a **monomorphized DECODE-ONLY checker `fn`** for the
/// handler `f` and yields its [`CheckFn`] pointer. It runs the SAME
/// `codec::decode::<In>(input)` as the [`typed!`] handler's first step — inferring
/// `In` from `f`'s single parameter — then DISCARDS the value WITHOUT calling `f`.
///
/// The pairing with [`typed!`] is what lets the CLI validate `--input` locally and
/// fail fast: a bad-shape input yields the SAME [`RunnerError::Decode`] the remote run
/// would (e.g. "missing field `text`") but with no Modal call and no body execution.
#[macro_export]
macro_rules! typed_check {
    ($f:path) => {{
        fn __check(input: &[u8]) -> ::core::result::Result<(), $crate::RunnerError> {
            // Infer `In` from `$f`'s single parameter WITHOUT calling it: coerce `$f`
            // to a `fn(In) -> R` pointer and decode into `In`. The handler is always a
            // single-`In` free fn (the macro's spread shim, or a Mode-A free fn), so
            // this coercion type-checks identically to the `typed!` handler's decode.
            fn __infer<In, R>(
                _f: fn(In) -> R,
                bytes: &[u8],
            ) -> ::core::result::Result<(), $crate::RunnerError>
            where
                In: ::serde::de::DeserializeOwned,
            {
                $crate::codec::decode::<In>(bytes).map(|_| ())
            }
            __infer($f, input)
        }
        __check as $crate::CheckFn
    }};
}

/// Macro-internal support used by [`typed!`] to choose, at compile time, between
/// the `Serialize` path (populates `details`) and the opaque path (`details =
/// null`). Not part of the stable API.
#[doc(hidden)]
pub mod __macro_support {
    use super::RunnerError;
    use serde::Serialize;

    /// Newtype the user error so an **inherent** constrained method (the `Serialize`
    /// path) and a **trait** blanket method (the opaque fallback) can share the name
    /// `to_runner_error`. At a monomorphic call site, an inherent method whose
    /// bounds are satisfied wins over the trait method; when the bounds are not
    /// satisfied (e.g. `anyhow::Error`, which is not `Serialize`), resolution falls
    /// through to the trait method. This is the stable autoref/inherent-priority
    /// specialization the `typed!` macro relies on.
    pub struct Wrap<E>(pub E);

    /// More-specific path: an **inherent** method available only when
    /// `E: Display + Serialize`. Populates `details` structurally (boundaries.md §2).
    impl<E: std::fmt::Display + Serialize> Wrap<E> {
        pub fn to_runner_error(&self) -> RunnerError {
            RunnerError::function(&self.0)
        }
    }

    /// Fallback path: a trait blanket method requiring only `Display`. Selected when
    /// the inherent `Serialize` method does not apply (e.g. `anyhow::Error`),
    /// yielding `details = null`.
    pub trait FunctionErrorOpaque {
        fn to_runner_error(&self) -> RunnerError;
    }

    impl<E: std::fmt::Display> FunctionErrorOpaque for Wrap<E> {
        fn to_runner_error(&self) -> RunnerError {
            RunnerError::function_opaque(&self.0)
        }
    }
}

/// A dispatch-only distributed registration entry collected by [`inventory`].
///
/// This runtime type carries only what the runner needs: an entrypoint name and
/// the monomorphized `typed!` wrapper `fn` pointer. Modal control-plane metadata
/// belongs to the facade crate's atomic macro registration record.
///
/// [`Registry::from_inventory`] collects every submission into the SAME
/// `BTreeMap<&'static str, HandlerFn>` the manual
/// `Registry::new().function(name, typed!(f))` builder produces, so both
/// registration paths converge on one dispatch path (boundaries.md §3). There is
/// no `dyn`, no `Box`, no vtable: `handler` is a bare `fn` pointer.
pub struct Registration {
    /// The entrypoint name (registry key).
    pub name: &'static str,
    /// The monomorphized [`typed!`] wrapper `fn` pointer.
    pub handler: HandlerFn,
    /// The monomorphized [`typed_check!`] DECODE-ONLY companion (`--check-input`
    /// local validation). `None` for hand-built registrations that predate the
    /// checker; such entrypoints skip local validation (degrade to the remote
    /// decode check) rather than false-reject.
    pub check: Option<CheckFn>,
    /// The SNAPSHOT-PRIME hook (forces this entrypoint's `#[cls]` singleton so its
    /// `#[enter]` runs inside the snapshot freeze window). `None` for plain functions
    /// and non-snapshot classes ⇒ inert; populated ONLY for snapshot-enabled `#[cls]`
    /// methods. The serve loop runs it on a `prime` frame (best-effort).
    pub snapshot_prime: Option<PrimeFn>,
}

inventory::collect!(Registration);

/// The handler registry: `BTreeMap<&'static str, HandlerFn>` (boundaries.md §3).
/// Static-str keys, fn-pointer values — no allocation, no `dyn`. Built with
/// [`Registry::new`] + [`Registry::function`]; **duplicate names are rejected**
/// (no silent last-write-wins).
#[derive(Default)]
pub struct Registry {
    handlers: BTreeMap<&'static str, HandlerFn>,
    /// Per-entrypoint DECODE-ONLY checker (the [`typed_check!`] companion of the
    /// handler), used by the `--check-input` mode. Parallel to `handlers`: an entry is
    /// present exactly when registered via [`Registry::function_checked`]. Entrypoints
    /// added via the handler-only [`Registry::function`] have no checker (older manual
    /// builders), so `--check-input` reports them as "no local validation available"
    /// and degrades to the remote decode check — never a false rejection.
    checks: BTreeMap<&'static str, CheckFn>,
    /// SNAPSHOT-PRIME hooks to run on a `{"kind":"prime"}` serve frame. A flat list
    /// (not keyed by name) because the serve loop fires ALL of them: each forces a
    /// `#[cls]` singleton's `#[enter]` inside the snapshot freeze window. Idempotence
    /// is owned by the underlying `OnceLock` `get_or_init`, so a class shared by N
    /// method-registrations is primed once even though N entries land here. Empty for
    /// any registry built without snapshot-enabled `#[cls]` methods, so a `prime` frame
    /// simply acks `{"primed":0}`.
    primes: Vec<PrimeFn>,
}

impl Registry {
    /// Create an empty registry.
    pub fn new() -> Self {
        Registry {
            handlers: BTreeMap::new(),
            checks: BTreeMap::new(),
            primes: Vec::new(),
        }
    }

    /// Assemble a [`Registry`] from every [`Registration`] submitted via
    /// [`inventory`] by the `#[modal_rust::function]` macro (boundaries.md §3,
    /// ergonomics E1).
    ///
    /// This converges on the SAME dispatch path as the manual builder: each
    /// collected entry is inserted through the same insertion logic as
    /// [`Registry::function`], so the resulting `BTreeMap<&'static str, HandlerFn>`
    /// is shape-identical to one built by hand.
    ///
    /// # Panics
    /// Panics (the SAME hard startup error as [`Registry::function`]) if two
    /// submissions share a name — duplicate names are rejected, never silently
    /// last-write-wins. This matters more in the macro/inventory world, where a
    /// duplicate `#[modal_rust::function(name = "x")]` is easy to write.
    pub fn from_inventory() -> Self {
        let mut registry = Registry::new();
        for registration in inventory::iter::<Registration> {
            registry = match registration.check {
                Some(check) => {
                    registry.function_checked(registration.name, registration.handler, check)
                }
                None => registry.function(registration.name, registration.handler),
            };
            if let Some(prime) = registration.snapshot_prime {
                registry = registry.snapshot_prime(prime);
            }
        }
        registry
    }

    /// Register a handler under `name`.
    ///
    /// # Panics
    /// Panics (a hard startup error) if `name` is already registered — duplicate
    /// names are rejected, never silently last-write-wins (boundaries.md §3).
    pub fn function(mut self, name: &'static str, handler: HandlerFn) -> Self {
        if self.handlers.insert(name, handler).is_some() {
            panic!("duplicate entrypoint registered: {name:?}");
        }
        self
    }

    /// Register a handler under `name` together with its DECODE-ONLY [`CheckFn`]
    /// companion (from [`typed_check!`]), enabling the `--check-input` local
    /// validation for this entrypoint. Identical to [`Registry::function`] for
    /// dispatch; it additionally records the checker.
    ///
    /// # Panics
    /// Panics (the SAME hard startup error as [`Registry::function`]) if `name` is
    /// already registered.
    pub fn function_checked(
        mut self,
        name: &'static str,
        handler: HandlerFn,
        check: CheckFn,
    ) -> Self {
        if self.handlers.insert(name, handler).is_some() {
            panic!("duplicate entrypoint registered: {name:?}");
        }
        self.checks.insert(name, check);
        self
    }

    /// Record a SNAPSHOT-PRIME hook to be fired (best-effort) on a `prime` serve
    /// frame. Builder-style (consumes + returns `self`) like [`Registry::function`].
    /// Unlike handlers, primes are NOT keyed by name and NEVER rejected for
    /// duplication: the serve loop calls every one, and the underlying `OnceLock`
    /// `get_or_init` makes repeated calls for the same class idempotent.
    pub fn snapshot_prime(mut self, prime: PrimeFn) -> Self {
        self.primes.push(prime);
        self
    }

    /// Look up a handler by name.
    pub fn get(&self, name: &str) -> Option<HandlerFn> {
        self.handlers.get(name).copied()
    }

    /// Look up the DECODE-ONLY checker for `name`, if one was registered (via
    /// [`Registry::function_checked`]). `None` means the entrypoint either does not
    /// exist OR was registered handler-only.
    pub fn get_check(&self, name: &str) -> Option<CheckFn> {
        self.checks.get(name).copied()
    }

    /// The registered entrypoint names, sorted (for diagnostics).
    pub fn names(&self) -> impl Iterator<Item = &&'static str> {
        self.handlers.keys()
    }
}

thread_local! {
    /// Per-thread captured panic info `(message, backtrace)`, populated by the
    /// process-wide panic hook (boundaries.md §2). Using a `thread_local!` instead
    /// of a process-global slot means parallel panics on different threads never
    /// race — each panicking thread writes only its own slot, which its own
    /// `catch_unwind` then reads. This matters under the test harness, which runs
    /// tests (including other deliberate panics) concurrently. The §3 concurrency
    /// caveat about a process-global slot is thereby resolved for the
    /// process-exits-after-one-call v0 path and made safe under concurrency.
    static PANIC_SLOT: RefCell<Option<(String, String)>> = const { RefCell::new(None) };
}

/// Ensures the panic hook is installed exactly once for the whole process
/// (boundaries.md §2). Installing via `Once` rather than swapping the hook per call
/// avoids the take/restore race that two concurrently panicking threads would hit.
static HOOK_INIT: Once = Once::new();

/// Install — exactly once — a process-wide panic hook that records the panicking
/// thread's `(message, backtrace)` into that thread's [`PANIC_SLOT`].
///
/// The hook always uses `Backtrace::force_capture()`, so the `panic` envelope's
/// `backtrace` is populated regardless of the `RUST_BACKTRACE` env var (no shim
/// env dependency). The hook only writes a thread-local; it neither prints nor
/// chains to a previous hook, so it stays quiet and never swallows or duplicates
/// unrelated panic output beyond suppressing the default stderr message.
fn install_panic_hook() {
    HOOK_INIT.call_once(|| {
        panic::set_hook(Box::new(|info| {
            let message = info.to_string();
            let backtrace = Backtrace::force_capture().to_string();
            // Guard against a poisoned/borrowed cell: if recording fails we still
            // unwind and `run_handler` falls back to a default message.
            let _ = PANIC_SLOT.try_with(|slot| {
                if let Ok(mut slot) = slot.try_borrow_mut() {
                    *slot = Some((message, backtrace));
                }
            });
        }));
    });
}

/// Run a single handler under `catch_unwind`, converting any of the five failure
/// modes into a [`RunnerError`]. A panic is captured (message + backtrace) via a
/// process-wide panic hook (installed once) and surfaced as [`RunnerError::Panic`]
/// (boundaries.md §2).
///
/// The captured panic info lives in a per-thread [`PANIC_SLOT`]: the hook writes the
/// panicking thread's info to its own slot, and this function — running on that same
/// thread after `catch_unwind` returns `Err` — reads it back. Because each thread
/// owns its slot, concurrent panics on other threads (e.g. parallel tests) cannot
/// clobber this call's capture.
fn run_handler(handler: HandlerFn, input: &[u8]) -> Result<Vec<u8>, RunnerError> {
    install_panic_hook();
    // Clear this thread's slot so a stale capture from a prior call can't leak in.
    PANIC_SLOT.with(|slot| {
        if let Ok(mut slot) = slot.try_borrow_mut() {
            *slot = None;
        }
    });
    let outcome = panic::catch_unwind(AssertUnwindSafe(|| handler(input)));
    match outcome {
        Ok(result) => result,
        Err(_) => {
            let captured =
                PANIC_SLOT.with(|slot| slot.try_borrow_mut().ok().and_then(|mut s| s.take()));
            let (message, backtrace) = captured
                .unwrap_or_else(|| ("panic (no message captured)".to_string(), String::new()));
            Err(RunnerError::Panic { message, backtrace })
        }
    }
}

/// The parsed runner invocation (boundaries.md §2):
/// `--entrypoint <name> ( --input-json <json> | --input-file <path> | --input-stdin )`.
struct Args {
    entrypoint: String,
    input: InputSource,
}

enum InputSource {
    Json(String),
    File(String),
    Stdin,
}

/// A flag-parse failure. The message goes to stderr; the process exits 1.
struct ArgError(String);

fn parse_args(argv: &[String]) -> Result<Args, ArgError> {
    let mut entrypoint: Option<String> = None;
    let mut input: Option<InputSource> = None;
    let mut i = 0;
    while i < argv.len() {
        let arg = &argv[i];
        match arg.as_str() {
            "--entrypoint" => {
                let v = argv
                    .get(i + 1)
                    .ok_or_else(|| ArgError("--entrypoint requires a value".to_string()))?;
                if entrypoint.is_some() {
                    return Err(ArgError("--entrypoint given more than once".to_string()));
                }
                entrypoint = Some(v.clone());
                i += 2;
            }
            "--input-json" => {
                let v = argv
                    .get(i + 1)
                    .ok_or_else(|| ArgError("--input-json requires a value".to_string()))?;
                if input.is_some() {
                    return Err(ArgError("multiple input sources given".to_string()));
                }
                input = Some(InputSource::Json(v.clone()));
                i += 2;
            }
            "--input-file" => {
                let v = argv
                    .get(i + 1)
                    .ok_or_else(|| ArgError("--input-file requires a value".to_string()))?;
                if input.is_some() {
                    return Err(ArgError("multiple input sources given".to_string()));
                }
                input = Some(InputSource::File(v.clone()));
                i += 2;
            }
            "--input-stdin" => {
                if input.is_some() {
                    return Err(ArgError("multiple input sources given".to_string()));
                }
                input = Some(InputSource::Stdin);
                i += 1;
            }
            other => {
                return Err(ArgError(format!("unrecognized argument: {other}")));
            }
        }
    }
    let entrypoint = entrypoint.ok_or_else(|| ArgError("--entrypoint is required".to_string()))?;
    let input = input.ok_or_else(|| {
        ArgError("one of --input-json, --input-file, or --input-stdin is required".to_string())
    })?;
    Ok(Args { entrypoint, input })
}

fn read_input(source: &InputSource) -> Result<Vec<u8>, ArgError> {
    match source {
        InputSource::Json(s) => Ok(s.clone().into_bytes()),
        InputSource::File(path) => std::fs::read(path)
            .map_err(|e| ArgError(format!("failed to read --input-file {path:?}: {e}"))),
        InputSource::Stdin => {
            use std::io::Read;
            let mut buf = Vec::new();
            std::io::stdin()
                .read_to_end(&mut buf)
                .map_err(|e| ArgError(format!("failed to read stdin: {e}")))?;
            Ok(buf)
        }
    }
}

/// Parse the runner flags, dispatch into `registry`, and print **exactly one** JSON
/// envelope to stdout (all diagnostics to stderr). Returns the process exit code:
/// `0` on success, `1` on any failure (boundaries.md §2). Installs a panic hook so
/// handler panics are captured as the `panic` error kind.
///
/// Precedence (frozen): top-level JSON parse → entrypoint lookup → decode `In` →
/// call → encode `Out`. A malformed-JSON input therefore yields `decode_error`
/// even when the entrypoint name is also unknown.
pub fn run_cli(registry: Registry) -> i32 {
    let argv: Vec<String> = std::env::args().skip(1).collect();
    run_cli_with_args(registry, &argv, &mut std::io::stdout())
}

/// The testable core of [`run_cli`]: takes explicit argv and an output sink so the
/// envelope can be captured in unit tests. Diagnostics still go to stderr.
pub fn run_cli_with_args<W: std::io::Write>(
    registry: Registry,
    argv: &[String],
    out: &mut W,
) -> i32 {
    // `--check-input`: DECODE-ONLY local validation. Parse the SAME
    // `--entrypoint`/`--input-*` flags, decode the input against the entrypoint's `In`
    // via the registered checker, and exit 0 (decodes) / 1 (does not) WITHOUT running
    // the handler body. Used by the CLI to fail fast before any Modal call. Writes its
    // one-line result to the SAME `out` sink as the run path (so it is testable).
    if argv.first().map(String::as_str) == Some("--check-input") {
        return run_check_input(&registry, &argv[1..], out);
    }

    let args = match parse_args(argv) {
        Ok(a) => a,
        Err(ArgError(msg)) => {
            eprintln!("modal_runner: argument error: {msg}");
            return 1;
        }
    };

    let raw_input = match read_input(&args.input) {
        Ok(b) => b,
        Err(ArgError(msg)) => {
            eprintln!("modal_runner: {msg}");
            return 1;
        }
    };

    // Frozen precedence: top-level JSON parse precedes entrypoint lookup. A
    // malformed-JSON input is a `decode_error` even when the entrypoint is unknown.
    if let Err(e) = serde_json::from_slice::<serde_json::Value>(&raw_input) {
        let err = RunnerError::Decode(e.to_string());
        return emit(out, &err.to_envelope(), 1);
    }

    // Entrypoint lookup precedes decode of `In`.
    let handler = match registry.get(&args.entrypoint) {
        Some(h) => h,
        None => {
            let err = RunnerError::UnknownEntrypoint(format!(
                "unknown entrypoint {:?}; known entrypoints: [{}]",
                args.entrypoint,
                registry
                    .names()
                    .map(|n| format!("{n:?}"))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
            return emit(out, &err.to_envelope(), 1);
        }
    };

    match run_handler(handler, &raw_input) {
        Ok(bytes) => {
            // The handler already encoded a valid JSON value via the codec; splice
            // it into the success envelope without a redundant string round-trip.
            let value: serde_json::Value = match serde_json::from_slice(&bytes) {
                Ok(v) => v,
                Err(e) => {
                    let err =
                        RunnerError::Encode(format!("handler output was not valid JSON: {e}"));
                    return emit(out, &err.to_envelope(), 1);
                }
            };
            let envelope = serde_json::json!({ "ok": true, "value": value });
            emit(out, &envelope, 0)
        }
        Err(err) => emit(out, &err.to_envelope(), 1),
    }
}

/// The DECODE-ONLY `--check-input` mode: parse `--entrypoint`/`--input-*`, decode the
/// input against the entrypoint's `In` via its registered [`CheckFn`], and write a
/// machine-readable result to stdout WITHOUT running the handler body. Returns the
/// process exit code (`0` decodes / `1` does not).
///
/// Output (one JSON line on stdout) so the CLI can react precisely:
/// - input decodes:            `{"ok":true}`                        → exit 0
/// - input does NOT decode:    the frozen `decode_error` envelope   → exit 1
/// - unknown entrypoint:       the frozen `unknown_entrypoint` env.  → exit 1
/// - entrypoint has no checker (handler-only registration): `{"ok":true,"checked":false}`
///   → exit 0, so the CLI degrades to the remote decode check rather than false-rejecting.
///
/// A malformed top-level JSON input is reported as `decode_error` (the SAME frozen
/// precedence as the run path), so `--input not-json` fails fast too.
fn run_check_input<W: std::io::Write>(registry: &Registry, argv: &[String], out: &mut W) -> i32 {
    let args = match parse_args(argv) {
        Ok(a) => a,
        Err(ArgError(msg)) => {
            eprintln!("modal_runner: argument error: {msg}");
            return 1;
        }
    };
    let raw_input = match read_input(&args.input) {
        Ok(b) => b,
        Err(ArgError(msg)) => {
            eprintln!("modal_runner: {msg}");
            return 1;
        }
    };
    run_check_input_inner(registry, &args.entrypoint, &raw_input, out)
}

/// Testable core of [`run_check_input`]: takes the entrypoint, raw input bytes, and an
/// output sink. Mirrors the run path's frozen precedence (top-level JSON parse →
/// entrypoint lookup → decode `In`) but stops at decode — the handler body never runs.
fn run_check_input_inner<W: std::io::Write>(
    registry: &Registry,
    entrypoint: &str,
    raw_input: &[u8],
    out: &mut W,
) -> i32 {
    // Frozen precedence: top-level JSON parse precedes entrypoint lookup.
    if let Err(e) = serde_json::from_slice::<serde_json::Value>(raw_input) {
        let err = RunnerError::Decode(e.to_string());
        return emit(out, &err.to_envelope(), 1);
    }
    // Entrypoint must exist (a typo fails fast, locally).
    if registry.get(entrypoint).is_none() {
        let err = RunnerError::UnknownEntrypoint(format!(
            "unknown entrypoint {:?}; known entrypoints: [{}]",
            entrypoint,
            registry
                .names()
                .map(|n| format!("{n:?}"))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        return emit(out, &err.to_envelope(), 1);
    }
    // Decode-only: a registered checker validates the input's shape WITHOUT calling the
    // body. A handler-only entrypoint (no checker) cannot be locally validated → report
    // `checked:false` so the CLI proceeds to the remote decode check.
    match registry.get_check(entrypoint) {
        Some(check) => match check(raw_input) {
            Ok(()) => emit(out, &serde_json::json!({ "ok": true }), 0),
            Err(err) => emit(out, &err.to_envelope(), 1),
        },
        None => emit(out, &serde_json::json!({ "ok": true, "checked": false }), 0),
    }
}

/// One framed serve REQUEST: an entrypoint name + the SAME per-call JSON input the
/// one-shot `--input-*` flag carries (boundaries.md §3, cls-design.md §5.1). The
/// serve loop reads one of these per line on stdin and writes exactly one frozen
/// envelope per response, never exiting between calls — so a generated process-global
/// `OnceLock` singleton (the entered `Cls` struct) survives across calls in a warm
/// container. ADDITIVE: the one-shot `--entrypoint/--input-*` path is untouched.
#[derive(serde::Deserialize)]
struct ServeRequest {
    /// The registry key (e.g. `"Embedder.embed"`); SAME lookup as one-shot.
    entrypoint: String,
    /// The per-call JSON input, verbatim (the SAME bytes `--input-json` would carry).
    input: String,
}

/// The OPTIONAL typed-frame discriminant (architecture §0): a forward-safe seam over
/// the SAME one-line serve framing. ONLY the `kind` field is read here; everything
/// else on the line is left for the per-kind parser, so a `request` frame is decoded
/// by the UNCHANGED [`ServeRequest`] exactly as before.
///
/// - absent / `"request"` ⇒ the EXISTING `{entrypoint,input}` request path (old
///   `kind`-less frames keep working byte-identically).
/// - `"prime"` ⇒ run the snapshot primes, ack `{"primed":<n>}`, serve no user request.
/// - a FUTURE `"restore"` lands as a new arm here (post-restore hooks) WITHOUT
///   touching the request path — the additive forward-safety mechanism.
#[derive(serde::Deserialize)]
struct FrameKind {
    #[serde(default)]
    kind: Option<String>,
}

/// Run the long-lived SERVE loop reading framed requests from stdin and writing one
/// frozen envelope per response on stdout (`modal_runner --serve`).
///
/// This is the ADDITIVE warm-reuse path (cls-design.md §2.1, Option 2a): the process
/// does NOT exit between calls, so a generated process-global `OnceLock` singleton —
/// the entered `Cls` struct — is built once (its `#[enter]` runs once) and reused by
/// every later method call in the same warm container. Free functions keep the
/// one-shot exec; only `Cls` methods (or, later, opt-in warm work) use serve. The
/// per-call `(entrypoint, input_json) -> envelope` contract, the five error kinds, and
/// FILE-mode are all UNCHANGED.
pub fn run_serve(registry: Registry) -> i32 {
    let stdin = std::io::stdin();
    let mut out = std::io::stdout();
    run_serve_with_io(registry, stdin.lock(), &mut out)
}

/// The testable core of [`run_serve`]: takes an explicit `BufRead` input and an output
/// sink so the loop can be driven in-process by unit tests (no Modal, no Python).
///
/// Framing: ONE request per input line, a JSON object
/// `{"entrypoint":"Embedder.embed","input":"{\"text\":\"hi\"}"}`; ONE response per
/// output line, the SAME frozen envelope the one-shot path emits
/// (`{"ok":true,"value":..}` or `{"ok":false,"error":{..}}`). The loop calls the SAME
/// [`run_handler`] (per-request `catch_unwind`) and the SAME [`Registry::get`], so the
/// taxonomy is byte-identical to one-shot. Crucially, the loop NEVER exits on a caught
/// panic, a decode failure, or an unknown entrypoint — it writes the failure envelope
/// and keeps serving, so one bad call cannot poison the warm container's singleton
/// (cls-design.md §10, the #1 correctness risk). Returns `0` on clean EOF.
pub fn run_serve_with_io<R: std::io::BufRead, W: std::io::Write>(
    registry: Registry,
    input: R,
    out: &mut W,
) -> i32 {
    for line in input.lines() {
        let line = match line {
            Ok(l) => l,
            Err(e) => {
                eprintln!("modal_runner --serve: failed to read request: {e}");
                return 1;
            }
        };
        // Skip blank lines (e.g. a trailing newline) without treating them as a
        // malformed frame.
        if line.trim().is_empty() {
            continue;
        }
        // Forward-safe seam (architecture §0): peek ONLY at an optional `kind`. A
        // `kind`-less (or `kind == "request"`) frame falls through to the UNCHANGED
        // request path below, so old serve frames decode byte-identically. A frame
        // that does not even parse as a JSON object here also falls through (the
        // request path emits the SAME `malformed serve request frame` decode_error as
        // before — no new error surface for old bad frames).
        if let Ok(FrameKind { kind: Some(kind) }) = serde_json::from_str::<FrameKind>(&line) {
            match kind.as_str() {
                "request" => {} // explicit request kind: fall through to the request path
                "prime" => {
                    serve_prime(&registry, out);
                    continue;
                }
                other => {
                    // An unknown kind is a degradeable signal, not a crash: report a
                    // decode_error frame and keep serving (a future `restore` kind is
                    // additive — it lands as a new arm above, never here).
                    let err = RunnerError::Decode(format!("unknown serve frame kind: {other:?}"));
                    let _ = emit_line(out, &err.to_envelope());
                    continue;
                }
            }
        }
        // A malformed FRAME (not a valid {entrypoint,input} object) is a decode_error
        // envelope, but the loop keeps serving the next request.
        let req: ServeRequest = match serde_json::from_str(&line) {
            Ok(r) => r,
            Err(e) => {
                let err = RunnerError::Decode(format!("malformed serve request frame: {e}"));
                let _ = emit_line(out, &err.to_envelope());
                continue;
            }
        };
        serve_one(&registry, &req, out);
    }
    0
}

/// Handle ONE `{"kind":"prime"}` frame: run every registered snapshot prime
/// BEST-EFFORT (a per-fn `Err` or panic is logged to stderr and skipped, NEVER
/// crashing the serve loop), then write exactly ONE ack line `{"primed":<n_ok>}`
/// where `n_ok` counts the primes that returned `Ok`. Serves no user request.
///
/// Each prime forces a `#[cls]` singleton's `get_or_init`, so its `#[enter]` runs
/// INSIDE Modal's memory-snapshot freeze window. Idempotence is owned by `OnceLock`:
/// a class shared by several method-registrations is primed once even though its
/// prime fn appears multiple times. If a prime never runs (frame never sent, child
/// died, or it errored), the FIRST real request still lazily runs `#[enter]` via the
/// existing `OnceLock` path — correctness holds; only the snapshot perf win is lost.
fn serve_prime<W: std::io::Write>(registry: &Registry, out: &mut W) {
    // Install the quiet panic hook so a panicking prime does not dump the default
    // message to stderr (we log our own one-line diagnostic and continue).
    install_panic_hook();
    let mut primed_ok: usize = 0;
    for prime in &registry.primes {
        // Catch a panicking prime too: a bad `#[enter]` must degrade to lazy init, not
        // poison the warm container's serve loop (architecture §4 correctness floor).
        let outcome = panic::catch_unwind(AssertUnwindSafe(prime));
        match outcome {
            Ok(Ok(())) => primed_ok += 1,
            Ok(Err(e)) => {
                eprintln!("modal_runner --serve: snapshot prime failed: {e}");
            }
            Err(_) => {
                eprintln!("modal_runner --serve: snapshot prime panicked");
            }
        }
    }
    let ack = serde_json::json!({ "primed": primed_ok });
    let _ = emit_line(out, &ack);
}

/// Handle ONE framed serve request: the SAME precedence as one-shot
/// (top-level JSON parse -> entrypoint lookup -> handler under `catch_unwind`),
/// writing exactly one envelope. NEVER exits the loop on failure.
fn serve_one<W: std::io::Write>(registry: &Registry, req: &ServeRequest, out: &mut W) {
    let raw_input = req.input.as_bytes();
    // Frozen precedence: top-level JSON parse precedes entrypoint lookup.
    if let Err(e) = serde_json::from_slice::<serde_json::Value>(raw_input) {
        let err = RunnerError::Decode(e.to_string());
        let _ = emit_line(out, &err.to_envelope());
        return;
    }
    let handler = match registry.get(&req.entrypoint) {
        Some(h) => h,
        None => {
            let err = RunnerError::UnknownEntrypoint(format!(
                "unknown entrypoint {:?}; known entrypoints: [{}]",
                req.entrypoint,
                registry
                    .names()
                    .map(|n| format!("{n:?}"))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
            let _ = emit_line(out, &err.to_envelope());
            return;
        }
    };
    // `run_handler` wraps the call in `catch_unwind`, so a panicking method yields a
    // `panic` envelope HERE and the loop above keeps serving — the singleton survives.
    match run_handler(handler, raw_input) {
        Ok(bytes) => {
            let value: serde_json::Value = match serde_json::from_slice(&bytes) {
                Ok(v) => v,
                Err(e) => {
                    let err =
                        RunnerError::Encode(format!("handler output was not valid JSON: {e}"));
                    let _ = emit_line(out, &err.to_envelope());
                    return;
                }
            };
            let envelope = serde_json::json!({ "ok": true, "value": value });
            let _ = emit_line(out, &envelope);
        }
        Err(err) => {
            let _ = emit_line(out, &err.to_envelope());
        }
    }
}

/// Write exactly one JSON envelope line for the serve loop. Unlike [`emit`], a write
/// failure does not abort the whole process — it returns `Err` and the caller keeps
/// serving (a broken pipe on one response should not poison the warm container).
fn emit_line<W: std::io::Write>(out: &mut W, envelope: &serde_json::Value) -> std::io::Result<()> {
    let s = serde_json::to_string(envelope)
        .unwrap_or_else(|e| format!(r#"{{"ok":false,"error":{{"kind":"encode_error","message":"failed to serialize envelope: {e}","details":null,"backtrace":""}}}}"#));
    writeln!(out, "{s}")?;
    out.flush()
}

/// Write exactly one JSON envelope (one line) to `out` and return `code`. Any write
/// failure is reported to stderr and forces exit 1.
fn emit<W: std::io::Write>(out: &mut W, envelope: &serde_json::Value, code: i32) -> i32 {
    match serde_json::to_string(envelope) {
        Ok(s) => {
            if let Err(e) = writeln!(out, "{s}") {
                eprintln!("modal_runner: failed to write envelope: {e}");
                return 1;
            }
            code
        }
        Err(e) => {
            eprintln!("modal_runner: failed to serialize envelope: {e}");
            1
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde::{Deserialize, Serialize};

    #[derive(Deserialize)]
    struct In {
        a: i64,
        b: i64,
    }

    #[derive(Serialize)]
    struct Out {
        sum: i64,
    }

    fn add(input: In) -> Result<Out, anyhow::Error> {
        Ok(Out {
            sum: input.a + input.b,
        })
    }

    #[derive(Debug, Serialize)]
    struct StructuredErr {
        code: u32,
        reason: String,
    }
    impl std::fmt::Display for StructuredErr {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "structured failure ({}): {}", self.code, self.reason)
        }
    }
    impl std::error::Error for StructuredErr {}

    fn fail_structured(_input: In) -> Result<Out, StructuredErr> {
        Err(StructuredErr {
            code: 7,
            reason: "boom".to_string(),
        })
    }

    fn fail_anyhow(_input: In) -> anyhow::Result<Out> {
        Err(anyhow::anyhow!("anyhow failure"))
    }

    #[derive(Serialize)]
    struct BadOut {
        // A tuple-keyed map has no JSON object representation -> encode_error
        // ("key must be a string"). int/bool keys would be coerced; NaN -> null.
        by_pair: std::collections::BTreeMap<(i32, i32), i32>,
    }
    fn bad_encode(_input: In) -> anyhow::Result<BadOut> {
        let mut by_pair = std::collections::BTreeMap::new();
        by_pair.insert((1, 2), 3);
        Ok(BadOut { by_pair })
    }

    fn will_panic(_input: In) -> anyhow::Result<Out> {
        panic!("deliberate test panic")
    }

    fn registry() -> Registry {
        Registry::new()
            .function("add", typed!(add))
            .function("fail_structured", typed!(fail_structured))
            .function("fail_anyhow", typed!(fail_anyhow))
            .function("bad_encode", typed!(bad_encode))
            .function("will_panic", typed!(will_panic))
    }

    fn run(args: &[&str]) -> (serde_json::Value, i32) {
        let argv: Vec<String> = args.iter().map(|s| s.to_string()).collect();
        let mut buf = Vec::new();
        let code = run_cli_with_args(registry(), &argv, &mut buf);
        let v: serde_json::Value = serde_json::from_slice(&buf).expect("one JSON envelope");
        (v, code)
    }

    #[test]
    fn success_add() {
        let (v, code) = run(&["--entrypoint", "add", "--input-json", r#"{"a":40,"b":2}"#]);
        assert_eq!(code, 0);
        assert_eq!(v, serde_json::json!({"ok": true, "value": {"sum": 42}}));
    }

    #[test]
    fn unknown_entrypoint() {
        let (v, code) = run(&["--entrypoint", "nope", "--input-json", "{}"]);
        assert_eq!(code, 1);
        assert_eq!(v["ok"], false);
        assert_eq!(v["error"]["kind"], "unknown_entrypoint");
        assert_eq!(v["error"]["details"], serde_json::Value::Null);
    }

    #[test]
    fn decode_error_malformed_json() {
        let (v, code) = run(&["--entrypoint", "add", "--input-json", "not-json"]);
        assert_eq!(code, 1);
        assert_eq!(v["error"]["kind"], "decode_error");
    }

    #[test]
    fn decode_error_wrong_shape() {
        let (v, code) = run(&["--entrypoint", "add", "--input-json", r#"{"a":1}"#]);
        assert_eq!(code, 1);
        assert_eq!(v["error"]["kind"], "decode_error");
    }

    #[test]
    fn function_error_anyhow_details_null() {
        let (v, code) = run(&[
            "--entrypoint",
            "fail_anyhow",
            "--input-json",
            r#"{"a":40,"b":2}"#,
        ]);
        assert_eq!(code, 1);
        assert_eq!(v["error"]["kind"], "function_error");
        assert_eq!(v["error"]["details"], serde_json::Value::Null);
        assert!(v["error"]["message"].as_str().unwrap().contains("anyhow"));
    }

    #[test]
    fn function_error_serialize_details_populated() {
        let (v, code) = run(&[
            "--entrypoint",
            "fail_structured",
            "--input-json",
            r#"{"a":40,"b":2}"#,
        ]);
        assert_eq!(code, 1);
        assert_eq!(v["error"]["kind"], "function_error");
        assert_eq!(
            v["error"]["details"],
            serde_json::json!({"code": 7, "reason": "boom"})
        );
    }

    #[test]
    fn encode_error_not_panic() {
        let (v, code) = run(&[
            "--entrypoint",
            "bad_encode",
            "--input-json",
            r#"{"a":40,"b":2}"#,
        ]);
        assert_eq!(code, 1);
        assert_eq!(v["error"]["kind"], "encode_error");
    }

    #[test]
    fn panic_captured_with_backtrace() {
        // No `RUST_BACKTRACE` mutation: the hook uses `Backtrace::force_capture()`,
        // which always captures, and the per-thread slot means this assertion is
        // robust even when other tests panic concurrently (boundaries.md §2/§3).
        let (v, code) = run(&[
            "--entrypoint",
            "will_panic",
            "--input-json",
            r#"{"a":0,"b":0}"#,
        ]);
        assert_eq!(code, 1);
        assert_eq!(v["error"]["kind"], "panic");
        assert!(v["error"]["message"]
            .as_str()
            .unwrap()
            .contains("deliberate test panic"));
        assert!(!v["error"]["backtrace"].as_str().unwrap().is_empty());
    }

    #[test]
    fn precedence_malformed_json_beats_unknown_entrypoint() {
        let (v, code) = run(&["--entrypoint", "nope", "--input-json", "not-json"]);
        assert_eq!(code, 1);
        assert_eq!(v["error"]["kind"], "decode_error");
    }

    #[test]
    #[should_panic(expected = "duplicate entrypoint")]
    fn duplicate_names_rejected() {
        let _ = Registry::new()
            .function("add", typed!(add))
            .function("add", typed!(add));
    }

    #[test]
    #[allow(clippy::assertions_on_constants)]
    fn not_panic_abort_profile() {
        // catch_unwind requires the unwind strategy; on `panic = "abort"` the
        // process would abort inside `will_panic` instead of producing the `panic`
        // envelope (boundaries.md §6). The success of `panic_captured_with_backtrace`
        // already proves unwind at test time; assert the cfg as an explicit signal.
        assert!(!cfg!(panic = "abort"), "build must not be panic = abort");
    }

    // ---- serve mode (the Cls load-once + crash-isolation seam, cls-design.md §6.3) ----

    mod serve {
        use super::*;
        use serde::Deserialize;
        use std::sync::atomic::{AtomicUsize, Ordering};
        use std::sync::OnceLock;

        // Each test gets its OWN `(counter, OnceLock)` pair so the suite stays
        // isolation-safe under the test harness's concurrent execution: an `OnceLock`
        // cannot be reset, and `#[enter] ran exactly once` is asserted via the counter
        // the `get_or_init` closure bumps exactly when it actually builds. The handlers
        // are `fn` pointers (no captures), so each "class" is a distinct static pair.
        // This faithfully models the generated per-class process-global singleton.

        #[derive(Deserialize)]
        struct EmbedIn {
            text: String,
        }

        // ---- class A: the load-once + crash-isolation proof ----
        static A_ENTER: AtomicUsize = AtomicUsize::new(0);
        static A_SINGLETON: OnceLock<usize> = OnceLock::new();
        fn a_singleton() -> &'static usize {
            A_SINGLETON.get_or_init(|| {
                A_ENTER.fetch_add(1, Ordering::SeqCst);
                7 // the "loaded model" state
            })
        }
        fn a_embed(input: EmbedIn) -> anyhow::Result<usize> {
            Ok(*a_singleton() + input.text.len())
        }
        fn a_dim(_input: serde_json::Value) -> anyhow::Result<usize> {
            Ok(*a_singleton())
        }
        fn a_boom(_input: serde_json::Value) -> anyhow::Result<usize> {
            let _ = a_singleton();
            panic!("deliberate method panic")
        }

        // ---- class B: the keep-serving-on-bad-frames proof (own singleton) ----
        static B_SINGLETON: OnceLock<usize> = OnceLock::new();
        fn b_dim(_input: serde_json::Value) -> anyhow::Result<usize> {
            Ok(*B_SINGLETON.get_or_init(|| 3))
        }
        fn b_embed(input: EmbedIn) -> anyhow::Result<usize> {
            Ok(*B_SINGLETON.get_or_init(|| 3) + input.text.len())
        }

        // ---- class C: the snapshot-PRIME proof (own singleton + prime fn) ----
        // Models a snapshot-enabled `#[cls]`: `c_prime` forces the singleton (running
        // `#[enter]` once) the way the macro-generated `__modal_snapshot_prime_<Class>`
        // does, and `c_dim` reuses it. The counter proves `#[enter]` ran EXACTLY once.
        static C_ENTER: AtomicUsize = AtomicUsize::new(0);
        static C_SINGLETON: OnceLock<usize> = OnceLock::new();
        fn c_singleton() -> &'static usize {
            C_SINGLETON.get_or_init(|| {
                C_ENTER.fetch_add(1, Ordering::SeqCst);
                42 // the "loaded model" state
            })
        }
        fn c_prime() -> Result<(), RunnerError> {
            let _ = c_singleton();
            Ok(())
        }
        fn c_dim(_input: serde_json::Value) -> anyhow::Result<usize> {
            Ok(*c_singleton())
        }

        fn drive(registry: Registry, frames: &[&str]) -> Vec<serde_json::Value> {
            let input = frames.join("\n");
            let mut out = Vec::new();
            let code = run_serve_with_io(registry, input.as_bytes(), &mut out);
            assert_eq!(code, 0, "serve loop returns 0 on clean EOF");
            String::from_utf8(out)
                .unwrap()
                .lines()
                .map(|l| serde_json::from_str(l).expect("one envelope per line"))
                .collect()
        }

        #[test]
        fn load_once_across_methods_then_crash_isolation() {
            // Two methods of one class, a panicking method, then a recovering call —
            // all in ONE serve process. Asserts: (a) one envelope per request, (b)
            // #[enter] ran ONCE (singleton reuse), (c) the panic yields a `panic`
            // envelope AND the loop keeps serving the next request (the singleton
            // survives the panic).
            let registry = Registry::new()
                .function("Embedder.embed", typed!(a_embed))
                .function("Embedder.dim", typed!(a_dim))
                .function("Embedder.boom", typed!(a_boom));
            let envelopes = drive(
                registry,
                &[
                    r#"{"entrypoint":"Embedder.embed","input":"{\"text\":\"hi\"}"}"#, // 7 + 2 = 9
                    r#"{"entrypoint":"Embedder.dim","input":"null"}"#,                // 7
                    r#"{"entrypoint":"Embedder.boom","input":"null"}"#,               // panic
                    r#"{"entrypoint":"Embedder.dim","input":"null"}"#, // 7 (survives)
                ],
            );
            assert_eq!(envelopes.len(), 4, "exactly one envelope per request");
            assert_eq!(envelopes[0], serde_json::json!({"ok": true, "value": 9}));
            assert_eq!(envelopes[1], serde_json::json!({"ok": true, "value": 7}));
            assert_eq!(envelopes[2]["ok"], false);
            assert_eq!(envelopes[2]["error"]["kind"], "panic");
            assert!(envelopes[2]["error"]["message"]
                .as_str()
                .unwrap()
                .contains("deliberate method panic"));
            // The loop kept serving AND the singleton survived the panic.
            assert_eq!(envelopes[3], serde_json::json!({"ok": true, "value": 7}));
            // The whole point: #[enter] ran exactly ONCE across all four calls.
            assert_eq!(
                A_ENTER.load(Ordering::SeqCst),
                1,
                "#[enter] (the OnceLock init) ran exactly once across calls"
            );
        }

        #[test]
        fn malformed_frame_and_unknown_entrypoint_keep_serving() {
            // A garbage frame, an unknown entrypoint, and a bad-shape input each yield
            // a failure envelope WITHOUT exiting the loop; a final good call succeeds.
            let registry = Registry::new()
                .function("Embedder.embed", typed!(b_embed))
                .function("Embedder.dim", typed!(b_dim));
            let envelopes = drive(
                registry,
                &[
                    r#"not even json"#,
                    r#"{"entrypoint":"Nope.method","input":"null"}"#,
                    r#"{"entrypoint":"Embedder.embed","input":"not-json"}"#,
                    r#"{"entrypoint":"Embedder.dim","input":"null"}"#,
                ],
            );
            assert_eq!(envelopes.len(), 4);
            assert_eq!(envelopes[0]["error"]["kind"], "decode_error"); // bad frame
            assert_eq!(envelopes[1]["error"]["kind"], "unknown_entrypoint");
            assert_eq!(envelopes[2]["error"]["kind"], "decode_error"); // bad input JSON
            assert_eq!(envelopes[3]["ok"], true); // loop still alive
        }

        #[test]
        fn blank_lines_are_skipped() {
            // A trailing/blank line must not be treated as a malformed frame.
            let registry = Registry::new().function("Embedder.dim", typed!(b_dim));
            let envelopes = drive(
                registry,
                &[
                    r#"{"entrypoint":"Embedder.dim","input":"null"}"#,
                    r#""#,
                    r#"   "#,
                ],
            );
            assert_eq!(envelopes.len(), 1, "blank lines produce no envelope");
            assert_eq!(envelopes[0]["ok"], true);
        }

        #[test]
        fn prime_frame_runs_enter_once_then_request_reuses_it() {
            // Architecture §0/§4: a `{"kind":"prime"}` frame forces the snapshot
            // `#[cls]` singleton (runs `#[enter]` once) and acks `{"primed":1}` WITHOUT
            // serving a user request; a following request reuses the primed singleton
            // (no second `#[enter]`). Two method-registrations share the ONE prime fn —
            // duplicate primes are idempotent via the `OnceLock`.
            C_ENTER.store(0, Ordering::SeqCst);
            let registry = Registry::new()
                .function("Counter.dim", typed!(c_dim))
                .function("Counter.also", typed!(c_dim))
                .snapshot_prime(c_prime)
                .snapshot_prime(c_prime); // same class registered twice -> primed once
            let envelopes = drive(
                registry,
                &[
                    r#"{"kind":"prime"}"#,                            // ack, no user request
                    r#"{"entrypoint":"Counter.dim","input":"null"}"#, // reuse, value 42
                ],
            );
            assert_eq!(envelopes.len(), 2, "one ack + one request envelope");
            // The prime acked with the count of primes that returned Ok (both did).
            assert_eq!(envelopes[0], serde_json::json!({"primed": 2}));
            // The request reused the primed singleton.
            assert_eq!(envelopes[1], serde_json::json!({"ok": true, "value": 42}));
            // The whole point: `#[enter]` (the `OnceLock` init) ran EXACTLY once across
            // the prime and the subsequent request — the prime warmed it, the request
            // reused it, and the duplicate prime did not re-enter.
            assert_eq!(
                C_ENTER.load(Ordering::SeqCst),
                1,
                "#[enter] ran exactly once: primed once, reused by the request"
            );
        }

        #[test]
        fn prime_frame_with_no_primes_acks_zero() {
            // A `prime` frame on a registry with NO snapshot primes is harmless: it acks
            // `{"primed":0}` and keeps serving (correctness floor — lazy `#[enter]`
            // still happens on the first real request).
            let registry = Registry::new().function("Embedder.dim", typed!(b_dim));
            let envelopes = drive(
                registry,
                &[
                    r#"{"kind":"prime"}"#,
                    r#"{"entrypoint":"Embedder.dim","input":"null"}"#,
                ],
            );
            assert_eq!(envelopes.len(), 2);
            assert_eq!(envelopes[0], serde_json::json!({"primed": 0}));
            assert_eq!(envelopes[1]["ok"], true);
        }

        #[test]
        fn explicit_request_kind_is_served_like_a_plain_frame() {
            // An explicit `kind == "request"` frame is served EXACTLY like a `kind`-less
            // one (forward-safety: old frames and new explicit-request frames converge).
            let registry = Registry::new().function("Embedder.dim", typed!(b_dim));
            let envelopes = drive(
                registry,
                &[r#"{"kind":"request","entrypoint":"Embedder.dim","input":"null"}"#],
            );
            assert_eq!(envelopes.len(), 1);
            assert_eq!(envelopes[0]["ok"], true);
        }

        #[test]
        fn unknown_kind_is_a_decode_error_and_keeps_serving() {
            // An unknown frame kind degrades to a decode_error envelope (not a crash);
            // the loop keeps serving the next request.
            let registry = Registry::new().function("Embedder.dim", typed!(b_dim));
            let envelopes = drive(
                registry,
                &[
                    r#"{"kind":"restore"}"#, // FUTURE kind, not built in v0
                    r#"{"entrypoint":"Embedder.dim","input":"null"}"#,
                ],
            );
            assert_eq!(envelopes.len(), 2);
            assert_eq!(envelopes[0]["error"]["kind"], "decode_error");
            assert_eq!(envelopes[1]["ok"], true); // loop still alive
        }
    }

    // ---- `--check-input`: DECODE-ONLY local validation (fail fast, no body run) ----
    mod check_input {
        use super::*;
        use std::sync::atomic::{AtomicUsize, Ordering};

        // A handler whose BODY bumps a counter, so a passing test proves the body did
        // NOT run during `--check-input` (decode-only).
        static BODY_RUNS: AtomicUsize = AtomicUsize::new(0);
        fn counting_add(input: In) -> Result<Out, anyhow::Error> {
            BODY_RUNS.fetch_add(1, Ordering::SeqCst);
            Ok(Out {
                sum: input.a + input.b,
            })
        }

        fn checked_registry() -> Registry {
            Registry::new().function_checked(
                "add",
                typed!(counting_add),
                typed_check!(counting_add),
            )
        }

        fn check(registry: Registry, entrypoint: &str, input: &str) -> (serde_json::Value, i32) {
            let mut buf = Vec::new();
            let code = run_check_input_inner(&registry, entrypoint, input.as_bytes(), &mut buf);
            let v: serde_json::Value = serde_json::from_slice(&buf).expect("one envelope");
            (v, code)
        }

        #[test]
        fn good_input_passes_without_running_body() {
            BODY_RUNS.store(0, Ordering::SeqCst);
            let (v, code) = check(checked_registry(), "add", r#"{"a":40,"b":2}"#);
            assert_eq!(code, 0);
            assert_eq!(v["ok"], true);
            // The DECODE-ONLY mode must NOT have invoked the handler body.
            assert_eq!(
                BODY_RUNS.load(Ordering::SeqCst),
                0,
                "--check-input must decode only, never run the handler body"
            );
        }

        #[test]
        fn bad_shape_input_fails_with_decode_error() {
            BODY_RUNS.store(0, Ordering::SeqCst);
            // Valid JSON, wrong shape (missing `b`) → decode_error, exit 1, no body run.
            let (v, code) = check(checked_registry(), "add", r#"{"a":1}"#);
            assert_eq!(code, 1);
            assert_eq!(v["ok"], false);
            assert_eq!(v["error"]["kind"], "decode_error");
            assert_eq!(BODY_RUNS.load(Ordering::SeqCst), 0);
        }

        #[test]
        fn malformed_json_input_fails_with_decode_error() {
            let (v, code) = check(checked_registry(), "add", "not-json");
            assert_eq!(code, 1);
            assert_eq!(v["error"]["kind"], "decode_error");
        }

        #[test]
        fn unknown_entrypoint_fails_locally() {
            let (v, code) = check(checked_registry(), "nope", "{}");
            assert_eq!(code, 1);
            assert_eq!(v["error"]["kind"], "unknown_entrypoint");
        }

        #[test]
        fn handler_only_entrypoint_reports_unchecked_and_passes() {
            // Registered via the handler-only `function` (no checker) → cannot validate
            // locally → `checked:false`, exit 0, so the CLI degrades to the remote check.
            let registry = Registry::new().function("add", typed!(counting_add));
            let (v, code) = check(registry, "add", r#"{"totally":"wrong"}"#);
            assert_eq!(code, 0, "no local checker → do not false-reject");
            assert_eq!(v["ok"], true);
            assert_eq!(v["checked"], false);
        }

        #[test]
        fn check_input_flag_routes_through_run_cli_with_args() {
            // The `--check-input` argv prefix is intercepted by `run_cli_with_args` and
            // never reaches one-shot dispatch: a bad-shape input exits 1 with no body run.
            BODY_RUNS.store(0, Ordering::SeqCst);
            let argv: Vec<String> = [
                "--check-input",
                "--entrypoint",
                "add",
                "--input-json",
                r#"{"a":1}"#,
            ]
            .iter()
            .map(|s| s.to_string())
            .collect();
            let mut buf = Vec::new();
            let code = run_cli_with_args(checked_registry(), &argv, &mut buf);
            assert_eq!(code, 1);
            let v: serde_json::Value = serde_json::from_slice(&buf).expect("envelope");
            assert_eq!(v["error"]["kind"], "decode_error");
            assert_eq!(BODY_RUNS.load(Ordering::SeqCst), 0);
        }
    }
}
