//! Request recording — the typed, queryable request log.
//!
//! Mirrors the Python servicer's `self.requests` + `ctx.get_requests("Method")`:
//! every RPC the mock hand-writes pushes a typed [`RecordedRequest`] into a shared
//! [`RequestLog`]. Tests query it generically by message type via the
//! [`FromRecorded`] trait, so a test can write `mock.requests::<FunctionCreateRequest>()`
//! / `mock.last::<FunctionCreateRequest>()` / `mock.took::<FunctionCreateRequest>()`.

use std::sync::{Arc, Mutex};

use crate::proto::api as gen;

/// One recorded request, typed. Variants for the RPCs the SDK uses on the
/// deploy / call / remote flow; extend as new ops appear. (The full set is small
/// and closed for our flow.)
///
/// The variants wrap the generated proto messages directly (e.g.
/// `ImageGetOrCreateRequest` is large), so the enum is sized to its biggest
/// variant. That is intentional for a test-only recording log: the typed
/// [`FromRecorded`] accessors hand out `&T` borrowed straight out of the variant,
/// so boxing the large variants would only complicate the query surface for no
/// real benefit at test scale (a handful of recorded requests).
#[allow(clippy::large_enum_variant)]
#[derive(Debug, Clone)]
pub enum RecordedRequest {
    /// `ClientHello` carries no fields the test needs, so it is recorded as a
    /// presence marker (count it with `mock.all_requests()`).
    ClientHello,
    AppGetOrCreate(gen::AppGetOrCreateRequest),
    AppCreate(gen::AppCreateRequest),
    AppPublish(gen::AppPublishRequest),
    EnvironmentGetOrCreate(gen::EnvironmentGetOrCreateRequest),
    BlobCreate(gen::BlobCreateRequest),
    MountGetOrCreate(gen::MountGetOrCreateRequest),
    MountPutFile(gen::MountPutFileRequest),
    ImageGetOrCreate(gen::ImageGetOrCreateRequest),
    FunctionPrecreate(gen::FunctionPrecreateRequest),
    FunctionCreate(gen::FunctionCreateRequest),
    FunctionGet(gen::FunctionGetRequest),
    FunctionMap(gen::FunctionMapRequest),
    FunctionPutInputs(gen::FunctionPutInputsRequest),
    FunctionGetOutputs(gen::FunctionGetOutputsRequest),
    SecretGetOrCreate(gen::SecretGetOrCreateRequest),
    VolumeGetOrCreate(gen::VolumeGetOrCreateRequest),
}

/// The shared, cloneable request log. A cheap `Arc<Mutex<..>>` clone shared
/// between the running server task and the test handle, so the test sees every
/// request the mock recorded.
#[derive(Clone, Default)]
pub struct RequestLog {
    inner: Arc<Mutex<Vec<RecordedRequest>>>,
}

impl RequestLog {
    /// Record one request (called by the servicer's hand-written RPCs).
    pub(crate) fn push(&self, r: RecordedRequest) {
        self.inner.lock().expect("request log poisoned").push(r);
    }

    /// All recorded requests in arrival order.
    pub fn all(&self) -> Vec<RecordedRequest> {
        self.inner.lock().expect("request log poisoned").clone()
    }

    /// Total number of recorded requests (all RPCs).
    pub fn len(&self) -> usize {
        self.inner.lock().expect("request log poisoned").len()
    }

    /// Whether NO request has been recorded yet.
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Every recorded request of type `T`, in order — e.g.
    /// `log.requests::<FunctionCreateRequest>()`.
    pub fn requests<T: FromRecorded + Clone>(&self) -> Vec<T> {
        self.inner
            .lock()
            .expect("request log poisoned")
            .iter()
            .filter_map(T::extract)
            .cloned()
            .collect()
    }

    /// The LAST recorded request of type `T` (`None` if absent) — e.g.
    /// `log.last::<FunctionCreateRequest>()`.
    pub fn last<T: FromRecorded + Clone>(&self) -> Option<T> {
        self.requests::<T>().pop()
    }

    /// Count of recorded requests of type `T` (Python's
    /// `len(ctx.get_requests("X"))`) — e.g. `log.took::<FunctionMapRequest>()`.
    pub fn took<T: FromRecorded + Clone>(&self) -> usize {
        self.requests::<T>().len()
    }
}

/// Maps a proto message type → its [`RecordedRequest`] variant, powering the
/// generic `requests::<T>()` / `last::<T>()` / `took::<T>()` query surface. One
/// tiny impl per recorded type, generated by [`impl_from_recorded!`].
pub trait FromRecorded: Sized {
    /// Borrow `self` out of a [`RecordedRequest`] if the variant matches.
    fn extract(r: &RecordedRequest) -> Option<&Self>;
}

/// Generate one `FromRecorded` impl per `MessageType => Variant` pair (one line
/// each) instead of hand-writing the boilerplate match arms.
macro_rules! impl_from_recorded {
    ( $( $msg:ident => $variant:ident ),+ $(,)? ) => {
        $(
            impl FromRecorded for gen::$msg {
                fn extract(r: &RecordedRequest) -> Option<&Self> {
                    match r {
                        RecordedRequest::$variant(v) => Some(v),
                        _ => None,
                    }
                }
            }
        )+
    };
}

impl_from_recorded! {
    AppGetOrCreateRequest        => AppGetOrCreate,
    AppCreateRequest             => AppCreate,
    AppPublishRequest            => AppPublish,
    EnvironmentGetOrCreateRequest => EnvironmentGetOrCreate,
    BlobCreateRequest            => BlobCreate,
    MountGetOrCreateRequest      => MountGetOrCreate,
    MountPutFileRequest          => MountPutFile,
    ImageGetOrCreateRequest      => ImageGetOrCreate,
    FunctionPrecreateRequest     => FunctionPrecreate,
    FunctionCreateRequest        => FunctionCreate,
    FunctionGetRequest           => FunctionGet,
    FunctionMapRequest           => FunctionMap,
    FunctionPutInputsRequest     => FunctionPutInputs,
    FunctionGetOutputsRequest    => FunctionGetOutputs,
    SecretGetOrCreateRequest     => SecretGetOrCreate,
    VolumeGetOrCreateRequest     => VolumeGetOrCreate,
}
