export const meta = {
  name: 'deploy-path',
  description: 'P5 deploy path: build at IMAGE-BUILD time (copy=True source as image context_mount + cargo build run_commands, bake the binary), deploy wrapper execs only the prebuilt binary, persistent AppPublish, then call -> {sum:42} with NO build at call time. Also fix run to use ephemeral apps so .remote() stops leaving persistent crash-loop-capable deploys.',
  phases: [
    { title: 'Design', detail: 'deploy_app.py + copy=True (context_mount) + deploy wrapper + run-vs-deploy app lifecycle -> spec' },
    { title: 'Implement', detail: 'deploy image (build-at-image-time) + deploy wrapper + App::deploy/call + ephemeral run; gates green (HARD GATE)' },
    { title: 'Live', detail: 'deploy add -> call == {sum:42}, cargo in BUILD logs + ABSENT at call; verify run no longer leaves a persistent deploy' },
    { title: 'Review', detail: 'parallel: DEPLOY build-boundary (cargo at image-build, never at call) + run-ephemeral; hygiene' },
  ],
}

const ROOT = '/Users/nicolas/devel/modal-rust'

const SHARED = [
  'You are building the DEPLOY path (P5) of modal-rust (repo root: ' + ROOT + '; git on main).',
  '',
  '## Where we are',
  'The RUN path is proven live: app.function("add").remote(AddInput{40,2}).await? == {sum:42} — source MOUNTED,',
  'cargo builds IN THE FUNCTION BODY at execution time. The lean first-party SDK (crates/modal-rust-sdk, no',
  'modal-rs dep) already has: auth/channel, CBOR, FILE-mode FunctionCreate (the 3 fixes), client-mount injection,',
  'mount_local_dir (local-dir UPLOAD via MountGetOrCreate+MountPutFile+BlobCreate+reqwest), AppPublish, FunctionGet,',
  'invoke (with retry_transient on every unary RPC). The facade crates/modal-rust has App/Function with .local()',
  '(in-process) and .remote() (run path, in remote.rs).',
  '',
  '## What this workflow builds: the DEPLOY boundary (the other half of "the product")',
  'DEPLOY = build at IMAGE-BUILD time; the deployed runtime NEVER runs cargo and NEVER mounts source — it execs only',
  'a prebuilt binary. `call` invokes a deployed function with no upload and no build. This is the HARD INVARIANT',
  '(boundaries.md, design stance #2). Concretely, port the PROVEN recipe in workpads/prototype/deploy_app.py:',
  '  - Image: from_registry("rust:1-slim", + python) ; COPY the source INTO an image layer (copy=True) ; first',
  '    run_commands = `cd /app/src && cargo build --release -p <PACKAGE> --bin modal_runner` (compile at BUILD time) ;',
  '    second run_commands = cp the built binary to a fixed path /app/modal_runner + chmod +x.',
  '  - Deploy wrapper (FILE mode): a Python module whose handler writes /tmp/in.json and execs ONLY /app/modal_runner',
  '    (NO cargo, NO source mount). Distinct from the RUN wrapper (which builds in-body).',
  '  - Persistent AppPublish (deploy) ; then call = FunctionGet(from_name) + invoke (already in the SDK).',
  '',
  '## The one genuinely-new SDK capability: copy=True (source into the image BUILD CONTEXT)',
  'The RUN path attaches the uploaded source as a runtime mount_id. DEPLOY instead needs the source available DURING',
  'the image build so `cargo build` can compile it at build time. Modal does this via the Image build CONTEXT:',
  'proto `message Image` has `context_mount_id = 15` (a single mount providing build context) and',
  '`repeated ImageContextFile context_files = 7` (inline small files). add_local_dir(copy=True) in the Python client',
  'uploads the dir as a mount and sets it as the image\'s context_mount_id, then the dockerfile does `COPY . <dest>`',
  'from that context. REUSE our existing mount_local_dir to upload, then set the returned mount_id as the image',
  'context_mount_id + add the COPY + cargo-build run_commands. Read references/modal-client/py/modal/image.py',
  '(the copy=True / add_local_dir(copy=True) path and how context_mount/COPY are wired) + the proto to confirm the',
  'exact fields. ImageSpec (crates/modal-rust-sdk/src/ops/image.rs) currently has from_registry + dockerfile',
  'run_commands (with_command/with_apt/pre_bake) + with_wrapper_module + with_pip_install_modal — extend it',
  'additively for a context mount + COPY + build commands.',
  '',
  '## ALSO FIX (root cause of crash-loop clutter the user flagged): run must be EPHEMERAL',
  'Right now the RUN path (.remote(), crates/modal-rust/src/remote.rs ensure_function) calls AppPublish — a',
  'PERSISTENT deploy — so every .remote() leaves a persistent app on Modal that lingers (and pre-fix ones crash-loop:',
  'a stale 11:30 deploy was found crash-looping on `ModuleNotFoundError: typing_extensions`). FIX: the RUN path must',
  'use an EPHEMERAL app (the SDK already has app_create_ephemeral) — create the function in an ephemeral app and',
  'invoke without AppPublish, so it auto-cleans and never lingers. If ephemeral invoke needs the app kept alive for',
  'the call, do that for the call duration then let it stop (or AppStop after). DEPLOY (this workflow\'s new path) is',
  'the ONLY path that uses persistent AppPublish. Verify the design: does FunctionCreate+invoke work in an ephemeral',
  'app without AppPublish? If not, the minimal correct fallback is AppStop after the run. Read deploy_app.py (deploy =',
  'persistent) vs dev_app.py (run = ephemeral `modal run`) for the intended split.',
  '',
  '## Ground-truth references (READ; never depend on — references/ is gitignored)',
  '- workpads/prototype/deploy_app.py — the PROVEN deploy recipe (copy=True + cargo at build + bake binary + bare',
  '  @app.function that execs /app/modal_runner). workpads/prototype/dev_app.py — the run (ephemeral) side.',
  '- references/modal-client/py/modal/image.py — add_local_dir(copy=True) / context_mount / COPY wiring.',
  '- crates/modal-rust-sdk/proto/api.proto — `message Image` (context_mount_id=15, context_files=7), ImageGetOrCreate.',
  '- crates/modal-rust-sdk/src/ops/{image.rs, local_dir.rs (mount_local_dir), function.rs, app.rs (app_create_ephemeral,',
  '  app_publish), invoke.rs, mount.rs}; crates/modal-rust/src/{remote.rs (ensure_function), app.rs, function.rs}.',
  '- workpads/shim-backend/knowledge.md (status, the 4 run-path bugs, the python-is-python3 + pip-deps findings).',
  '- workpads/architecture/boundaries.md — the run-vs-deploy build boundary invariant.',
  '',
  '## FROZEN invariants — do NOT change',
  '- The runner CLI protocol, Registry/macros, and the build boundary. Do not rewrite working .local()/.remote() or',
  '  the proven SDK ops; ADD the deploy path + the additive copy=True/context support + the ephemeral-run fix.',
  '- The deployed runtime MUST NOT run cargo and MUST NOT mount source. cargo runs ONLY at image-build time for deploy.',
  '',
  '## Verification rules (WORKING.md)',
  '- Gates on default-members: cargo fmt --check ; cargo clippy --all-targets -- -D warnings ; cargo build ; cargo',
  '  test. Keep no-CUDA CI green. Live tests behind #[ignore] + the live feature.',
  '- Reuse retry_transient (already added) for all new RPCs. Modal flakiness => RETRY, never block. DRIVE the live',
  '  proof to a terminal result (do not punt to a background monitor and return).',
  '- The live deploy test must use a STABLE app name (e.g. modal-rust-add-deploy) so re-runs REPLACE it (no',
  '  accumulation), and the image is the FIXED one (works, no crash-loop). Do not leave broken deploys behind.',
  '',
  '## How to return',
  'End with: "RESULT: <STATUS> — <one-line>". Build phases STATUS in {BUILD_GREEN, BUILD_FAILED} + exact cargo output.',
  'Live: the decoded result + the cargo-at-build-not-call evidence, or the precise error after retries. Cite paths.',
].join('\n')

phase('Design')
const design = await parallel([
  () => agent(SHARED + '\n\n' + [
    'YOUR TASK (Design / deploy image copy=True + deploy wrapper). Read workpads/prototype/deploy_app.py,',
    'references/modal-client/py/modal/image.py (add_local_dir(copy=True) / context_mount / COPY), the proto',
    '`message Image` (context_mount_id=15, context_files=7) + ImageGetOrCreate, and crates/modal-rust-sdk/src/ops/',
    '{image.rs, local_dir.rs}. Produce a PRECISE spec for:',
    '- Extending ImageSpec (additively) to express a DEPLOY image: set the uploaded source mount (from mount_local_dir)',
    '  as the image context_mount_id, add a `COPY` dockerfile step bringing the source to /app/src, then run_commands',
    '  = [cd /app/src && cargo build --release -p <PACKAGE> --bin modal_runner ; cp .../modal_runner /app/modal_runner',
    '  && chmod +x]. cargo runs at IMAGE-BUILD time. Confirm exact ImageGetOrCreate field wiring for context_mount_id.',
    '- The DEPLOY FILE-mode wrapper module (distinct from the run wrapper): handler writes /tmp/in.json and execs ONLY',
    '  /app/modal_runner --entrypoint <name> --input-file /tmp/in.json ; returns the envelope. NO cargo, NO source mount.',
    '- Python provisioning for the deploy image (reuse the proven approach: apt python3 + python-is-python3 +',
    '  pip --break-system-packages modal, OR add_python). Keep what already works on the run image.',
    'Cite file:line + proto fields. RESULT: SPEC_DONE — deploy image + deploy wrapper spec',
  ].join('\n'), { phase: 'Design', label: 'design:deploy-image' }),

  () => agent(SHARED + '\n\n' + [
    'YOUR TASK (Design / deploy+call API and the run-vs-deploy app lifecycle fix). Read crates/modal-rust/src/',
    '{remote.rs (ensure_function — note it calls app_publish), app.rs, function.rs}, crates/modal-rust-sdk/src/ops/',
    '{app.rs (app_create_ephemeral, app_get_or_create, app_publish), function.rs, invoke.rs}, and deploy_app.py vs',
    'dev_app.py (deploy=persistent vs run=ephemeral). Produce a PRECISE spec for:',
    '- The DEPLOY surface: App::deploy(name) (or Function deploy) that builds the deploy image (copy=True + cargo at',
    '  build), FunctionPrecreate + FunctionCreate(FILE, deploy wrapper, image_id, NO source runtime mount, client',
    '  mount only), then PERSISTENT AppPublish under a STABLE app name; and call = function_from_name + invoke',
    '  (already in the SDK). The deployed function does NOT build or mount source at call time.',
    '- The RUN-vs-DEPLOY app lifecycle FIX: change the RUN path (.remote()/ensure_function) to use an EPHEMERAL app',
    '  (app_create_ephemeral) and NOT AppPublish, so it stops leaving persistent crash-loop-capable deploys. Verify',
    '  whether FunctionCreate+invoke works in an ephemeral app without publish; if the ephemeral app needs to stay',
    '  alive for the call, specify how (hold it for the invoke, then let it auto-stop / AppStop). Persistent AppPublish',
    '  becomes DEPLOY-only. Specify the minimal, correct change to remote.rs/app.rs.',
    'Cite file:line. RESULT: SPEC_DONE — deploy/call API + ephemeral-run fix spec',
  ].join('\n'), { phase: 'Design', label: 'design:deploy-lifecycle' }),
])

const spec = await agent(SHARED + '\n\n' + [
  'YOUR TASK (Synthesize). Merge the two notes into ONE build-ready spec and WRITE it to',
  ROOT + '/workpads/shim-backend/deploy-build-spec.md (overwrite if present): the deploy ImageSpec extension',
  '(context_mount + COPY + cargo-at-build + bake binary), the deploy FILE-mode wrapper, App::deploy + call, and the',
  'run-vs-deploy app lifecycle fix (run = ephemeral, deploy = persistent AppPublish). Preserve the DEPLOY boundary',
  '(cargo at image-build, never at call; deployed runtime execs only the prebuilt binary, no source mount). Resolve',
  'contradictions (prefer the proven deploy_app.py recipe). Keep it tight.',
  '',
  '=== DEPLOY IMAGE + WRAPPER NOTE ===',
  (design[0] || '(missing)'),
  '',
  '=== DEPLOY/CALL API + EPHEMERAL-RUN NOTE ===',
  (design[1] || '(missing)'),
  '',
  'RESULT: SPEC_DONE — wrote deploy-build-spec.md',
].join('\n'), { phase: 'Design', label: 'design:synthesize' })

phase('Implement')
const impl = await agent(SHARED + '\n\n' + [
  'The spec is at ' + ROOT + '/workpads/shim-backend/deploy-build-spec.md — READ IT FIRST.',
  '',
  'YOUR TASK (Implement the deploy path + ephemeral-run fix — HARD GATE on offline gates). Per the spec:',
  '1. Extend ImageSpec (additive) for a deploy image: context_mount_id (the uploaded source mount) + COPY +',
  '   run_commands(cargo build --release -p <pkg> --bin modal_runner ; bake to /app/modal_runner). cargo at BUILD time.',
  '2. Add the deploy FILE-mode wrapper (execs ONLY /app/modal_runner; no cargo, no source mount).',
  '3. Add App::deploy(name)/Function deploy path: build deploy image -> precreate -> FunctionCreate(FILE, deploy',
  '   wrapper, client mount only) -> persistent AppPublish under a STABLE name; call = from_name + invoke. Reuse',
  '   retry_transient for all RPCs.',
  '4. Fix the RUN path (.remote()/ensure_function) to use an EPHEMERAL app (no AppPublish) so it stops leaving',
  '   persistent deploys. Persistent AppPublish is DEPLOY-only now.',
  'Do NOT let the deployed runtime run cargo or mount source. Do NOT rewrite working .local()/.remote() logic beyond',
  'the ephemeral-app change + additive deploy code.',
  'VERIFY (offline hard): cargo fmt --check ; cargo clippy --all-targets -- -D warnings ; cargo build ; cargo test',
  '(all default-members) — all green. Paste exact output.',
  'RESULT: BUILD_GREEN — deploy path (copy=True build-at-image-time + deploy wrapper + App::deploy/call) + ephemeral run compile + test green',
  '   (or BUILD_FAILED — <reason>)',
].join('\n'), { phase: 'Implement', label: 'deploy-impl' })

const implGreen = /RESULT:\s*BUILD_GREEN/i.test(impl || '')
let live = null
if (!implGreen) {
  log('Implement HARD GATE not green — deploy path did not compile. Skipping Live; Review documents the blocker.')
} else {
  phase('Live')
  live = await agent(SHARED + '\n\n' + [
    'The deploy path + ephemeral-run fix are implemented and compile. Run the LIVE proof and DRIVE IT TO A TERMINAL',
    'RESULT yourself (do NOT leave a background monitor and return).',
    '',
    'YOUR TASK (LIVE deploy + call proof). Write/run a live test (behind #[ignore] + the live feature) that:',
    '  1. App::deploy("modal-rust-add-deploy") — builds the deploy image (cargo at IMAGE-BUILD time), persistent',
    '     AppPublish under that STABLE name (re-runs replace it; no accumulation).',
    '  2. call("add", AddInput{a:40,b:2}) on the deployed function -> AddOutput{sum:42}, with NO build at call time.',
    'Prove the DEPLOY boundary from logs: cargo appears in the IMAGE-BUILD logs and is ABSENT from the call/runtime',
    'logs (the deployed body execs only /app/modal_runner). Also confirm the RUN path (.remote()) no longer leaves a',
    'persistent deployed app (after a .remote(), `modal app list` shows no new lingering deployed app — it was',
    'ephemeral/auto-stopped). Modal flakiness => RETRY (the retry_transient layer + Modal image caching help); be',
    'patient on the first build. If a real bug surfaces, make the MINIMAL fix and re-verify offline gates.',
    'Capture: the decoded {sum:42} from call; the cargo-in-build-not-in-call evidence; the no-lingering-deploy check.',
    'RESULT: BUILD_GREEN — deploy+call live == {sum:42}, cargo at build-not-call confirmed, run leaves no persistent deploy',
    '   (or BUILD_FAILED — <real bug>   or INFRA_BLOCKED — <transient after N retries>)',
  ].join('\n'), { phase: 'Live', label: 'live-deploy-call' })
}

phase('Review')
const reviews = await parallel([
  () => agent(SHARED + '\n\n' + [
    'YOUR TASK (Review / DEPLOY build-boundary — the critical invariant). Verify against the code + deploy_app.py +',
    'workpads/architecture/boundaries.md:',
    '- cargo build runs ONLY at IMAGE-BUILD time for deploy (in the image run_commands), NEVER in the deployed function',
    '  body / at call time. The deployed wrapper execs ONLY the prebuilt /app/modal_runner; it does not invoke cargo',
    '  and does not mount source. Quote the deploy wrapper + the image build commands.',
    '- The source reaches the image via copy=True (context_mount_id / COPY at build), NOT a runtime mount.',
    '- The RUN path now uses an EPHEMERAL app (no AppPublish) so it does not leave persistent deploys; persistent',
    '  AppPublish is deploy-only. Confirm in remote.rs/app.rs.',
    '- FILE mode + the 3 fixes + retry_transient are intact on the new RPCs.',
    'RESULT: PASS — deploy boundary intact + run ephemeral  (or FAIL — <what violates it>)',
  ].join('\n'), { phase: 'Review', label: 'review:deploy-boundary' }),

  () => agent(SHARED + '\n\n' + [
    'YOUR TASK (Review / hygiene — RUN the gates). From ' + ROOT + ' report exact output + exit status:',
    '- cargo fmt --check ; cargo clippy --all-targets -- -D warnings ; cargo build ; cargo test  (default-members).',
    'Confirm example-burn-add still excluded from default-members; live tests #[ignore]+live-feature gated; no',
    'hand-written file grossly exceeds ~500 LOC. Report failures verbatim.',
    'RESULT: PASS — gates green  (or FAIL — <exact failing command + output>)',
  ].join('\n'), { phase: 'Review', label: 'review:hygiene' }),
])

return { impl_green: implGreen, impl, live, reviews }
